# This workflow will do a clean install of node dependencies,
# build the application and deploy it to production
# when a new version (git tag) is released

name: Build & Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Build app
      run: |
        printf "VITE_SB_KEY=${{ secrets.SB_KEY }}\nVITE_SB_URL=${{ secrets.SB_URL }}" >> .env
        npm install
        npm run build
    - name: Push Build files to production
      uses: burnett01/rsync-deployments@7.0.2
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
        remote_key_pass: ${{ secrets.DEPLOY_SSH_PHRASE }}
